version: '3'

services:
  traefik:
    #Traefik docker image version 
    image: traefik:v2.10

    ports:
      # Exposes port 80 for incoming web requests
      - "80:80"
      - "443:443"
      # This is for the dashboard
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml
  
  # Add whoami service
  catapp:
    # A container that exposes an API to show its IP address.
    image: mikesir87/cats:1.0
    #  We set a label to tell Traefik to assign a hostname to the new service
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.catapp.rule=Host(`localhost`)"
      - "traefik.http.routers.catapp.entrypoints=web"
      - "traefik.http.routers.catapp.service=catapp"
      - "traefik.http.services.catapp.loadbalancer.server.port=5000"
