version: '3'

services:
  traefik:
    #Traefik docker image version 
    image: traefik:v2.10

    ports:
      # Exposes port 80 for incoming web requests
      - "80:80"
      - "443:443"
      # This is for the dashboard
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml
  
  # Add whoami service
  catapp:
    # A container that exposes an API to show its IP address.
    image: mikesir87/cats:2.0
    #  We set a label to tell Traefik to assign a hostname to the new service
    labels:
      - "traefik.enable=true"
      # Routers
      - "traefik.http.routers.catapp.rule=Host(`catapp.localhost`)"
      - "traefik.http.routers.catapp.service=catapp"
      - "traefik.http.routers.catapp.entrypoints=web"
      - "traefik.http.routers.catapp.middlewares=test-auth"
# Services
      - "traefik.http.services.catapp.loadbalancer.server.port=5000"
# Middleware BasicAuth
      - "traefik.http.middlewares.test-auth.basicauth.users=traefik:$$apr1$$.zPbdVg8$$LcHeyCZElH.JfxkxxlMPI.,user2:$$apr1$$XDrP1Fb1$$SZqSEjvNYW44vgJgI3iEP0"
       # user1: traefik password: training
       # user2: user2 password: test123
       # Create hash password -> echo $(htpasswd -nb user2 test123) | sed -e s/\\$/\\$\\$/g
