# API and Dashboard config
api:
  dashboard: true
  insecure: true

######### end ##########

# Docker configuration backend
providers:
  docker:
    exposedByDefault: false


###### end #########

# Traefik Logging
log:
  level: INFO

# Entrypoint
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
